version: "3"
services:
  hygieia-mongo:
    image: mongo:4.2
    container_name: hygieia-mongo
    user: "501:20"
    command: [ "--replSet", "my-replica-set", "--bind_ip_all", "--port", "27017" ]
    networks:
      - my-network
    volumes:
      - ./data/hygieia-mongo:/data/db:rw
    expose:
      - 27017
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"localhost:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
    restart: always

  hygieia-app:
    build: .
    networks:
      - my-network
    depends_on:
      - hygieia-mongo
    ports:
      - "2000:2000"
    restart: always

networks:
  my-network:
    driver: bridge